spring:
  datasource:
    url: jdbc:mysql://121.36.77.21:5019/dfq?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: dfq5019.
    hikari:
      minimum-idle: 5
      maximum-pool-size: 100
      idle-timeout: 30000
      validation-timeout: 250
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1



  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 8000


mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
